<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MagacinERP.Core\MagacinERP.Core.csproj" />
    <ProjectReference Include="..\MagacinERP.Services\MagacinERP.Services.csproj" />
    <ProjectReference Include="..\MagacinERP.DataAccess\MagacinERP.DataAccess.csproj" />
  </ItemGroup>

</Project>
